server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      # 开启Http编码支持
      enabled: true
      # 强制在请求和响应中使用指定的字符编码
      force: true
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet_home
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


