server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      # 开启Http编码支持
      enabled: true
      # 强制在请求和响应中使用指定的字符编码
      force: true
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet_home
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345678
    database: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2MB
      location: D:\Project\tmp\PetHome\upload\tmp
  mvc:
    static-path-pattern: /static/**
# 数据库相关配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    banner: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  page-size-zero: true
#Api文档相关配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.pethome.controller
  paths-to-match: /**

# 文件上传配置
file:
  upload:
    # 建议使用斜杠而非反斜杠，因为反斜杠需要转义，反斜杠必须使用两个反斜杠才会被正确解析
    root-path: D:/Project/tmp/PetHome/upload
    # 开头加不加斜杠都可以，注意不要有空格
    image-folder: image
    video-folder: video
    pdf-folder: pdf
    txt-folder: txt
    other-folder: other
