server:
  port: 8080
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet_home
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
  security:
    user:
      name: root
      password: 12345678
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


